name: Flutter build on tag and publish
on:
  push:
    tags:
      - 'v*' # This will reference the pub.dev version

jobs:
  flutter-version:
    name: Parse Flutter's version
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Flutter version
        id: flutter-version
        run: |
          FLUTTER_VERSION=$(jq -r .flutter .fvmrc)
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_OUTPUT


  publish-pub:
    name: Publish on pub.dev
    runs-on: ubuntu-latest
    needs: flutter-version
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract
        run: echo "TAG_VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Parse Flutter version
        id: flutter-version
        run: |
          FLUTTER_VERSION=$(jq -r .flutter .fvmrc)
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> "$GITHUB_OUTPUT"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          channel: stable

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Set SDK version in pubspec.yaml
        run: |
          sed -i "s/^version: .*/version: ${{ steps.extract.outputs.TAG_VERSION }}/" pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        run: dart pub publish --force

